### ISSUE TITLE
does not compile on kernel 4.15

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/gpcieuni-basedriver#2]
The driver uses constants which are platform specific and not part of the public interface but implementation details. They have been removed in recent kernel versions (>= 4.13?). Fix the driver to only use the foreseen interface.

~~~
/home/msk_jenkins/gpcieuni-basedriver/pcieuni_buffer.c: In function ‘pcieuni_buffer_destroy’:
/home/msk_jenkins/gpcieuni-basedriver/pcieuni_buffer.c:211:35: error: ‘DMA_ERROR_CODE’ undeclared (first use in this function); did you mean ‘DPM_ORDER_NONE’?
         if (buffer->dma_handle != DMA_ERROR_CODE)
                                   ^~~~~~~~~~~~~~
                                   DPM_ORDER_NONE
~~~

**Comment by killenb** [comment]
Resolved in 00.14
