### ISSUE TITLE
Driver does not compile on kernel 5.6

### ISSUE THREAD

**Issue by phako** [ChimeraTK/gpcieuni-basedriver#4]
```
In file included from /scratch/source/gpcieuni_drv.c:4:
/scratch/source/pcieuni_io.h:28:26: error: field 'start_time' has incomplete type
   28 |         struct timeval   start_time;
      |                          ^~~~~~~~~~
/scratch/source/pcieuni_io.h:29:26: error: field 'stop_time' has incomplete type
   29 |         struct timeval   stop_time;
      |                          ^~~~~~~~~
make[6]: *** [/usr/src/linux-5.6.0-1/scripts/Makefile.build:269: /scratch/source/gpcieuni_drv.o] Error 1
make[5]: *** [/usr/src/linux-5.6.0-1/Makefile:1698: /scratch/source] Error 2
make[4]: *** [../../../linux-5.6.0-1/Makefile:180: sub-make] Error 2
make[4]: Leaving directory '/usr/src/linux-5.6.0-1-obj/x86_64/default
```

**Comment by phako** [comment]
Related to https://www.kernel.org/doc/html/latest/core-api/timekeeping.html#deprecated-time-interfaces which is also hiding away the definition of `struct timeval` due to the Y2038 problem
